/**
 * Fix TimeRecords and OvertimeRequests where date was set from clock-OUT time
 * instead of session START time.
 *
 * Problem: For shifts that crossed midnight (e.g. started Apr 15, ended Apr 16 at 2:10 AM),
 * the TimeRecord.date and OvertimeRequest.date were stored as Apr 16 (clock-out date)
 * instead of Apr 15 (session start date). This caused:
 *   - Regular hours showing as 0h on the actual work day
 *   - Overtime appearing on the next day's active session row
 *
 * Fix: For each TimeRecord where date != actualStart date (in client timezone),
 * update date to match actualStart date. Also fix linked OvertimeRequests.
 *
 * Run (dry-run first!):
 *   DRY_RUN=true npx tsx src/scripts/fix-crossmidnight-timerecord-dates.ts
 *
 * Then apply:
 *   npx tsx src/scripts/fix-crossmidnight-timerecord-dates.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const DRY_RUN = process.env.DRY_RUN === 'true';

function toDateUTC(d: Date, tz: string): Date {
  const localStr = d.toLocaleDateString('en-CA', { timeZone: tz }); // YYYY-MM-DD
  const [y, m, day] = localStr.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, day));
}

function fmtDate(d: Date) {
  return d.toISOString().split('T')[0];
}

async function main() {
  console.log(`[Fix] Mode: ${DRY_RUN ? 'DRY RUN (no writes)' : 'LIVE (will write to DB)'}`);
  console.log('[Fix] Finding TimeRecords with cross-midnight date mismatch...\n');

  const records = await prisma.timeRecord.findMany({
    where: {
      actualStart: { not: null },
    },
    include: {
      client: { select: { timezone: true } },
    },
    orderBy: { date: 'asc' },
  });

  let fixed = 0;
  let skipped = 0;
  let conflicts = 0;

  for (const record of records) {
    if (!record.actualStart) continue;

    const tz = record.client?.timezone || 'UTC';
    const correctDate = toDateUTC(record.actualStart, tz);
    const storedDate = new Date(record.date);

    // Compare dates (both are UTC midnight)
    if (correctDate.getTime() === storedDate.getTime()) continue; // already correct

    const storedStr = fmtDate(storedDate);
    const correctStr = fmtDate(correctDate);

    console.log(`[Mismatch] TimeRecord ${record.id}`);
    console.log(`  Employee: ${record.employeeId} | Client: ${record.clientId}`);
    console.log(`  Stored date: ${storedStr} → Correct date: ${correctStr}`);
    console.log(`  actualStart: ${record.actualStart.toISOString()} | actualEnd: ${record.actualEnd?.toISOString() ?? 'active'}`);

    // Check for conflict: is there already a TimeRecord on the correct date?
    const conflicting = await prisma.timeRecord.findUnique({
      where: {
        employeeId_clientId_date: {
          employeeId: record.employeeId,
          clientId: record.clientId,
          date: correctDate,
        },
      },
    });

    if (conflicting && conflicting.id !== record.id) {
      console.log(`  ⚠ CONFLICT: A record already exists for ${correctStr} (id: ${conflicting.id}) — SKIPPING`);
      conflicts++;
      continue;
    }

    // Find OvertimeRequests on the wrong date for this employee/client
    // They were auto-created at clock-out time, so their date is the stored (wrong) date.
    // Only fix auto-generated ones — manually pre-requested OTs may have intentional dates.
    const wrongDateOTs = await prisma.overtimeRequest.findMany({
      where: {
        employeeId: record.employeeId,
        clientId: record.clientId,
        date: storedDate,
        isAutoGenerated: true,
      },
    });

    if (!DRY_RUN) {
      // Update TimeRecord date
      await prisma.timeRecord.update({
        where: { id: record.id },
        data: { date: correctDate },
      });

      // Update linked OvertimeRequests
      for (const ot of wrongDateOTs) {
        await prisma.overtimeRequest.update({
          where: { id: ot.id },
          data: { date: correctDate },
        });
        console.log(`  Fixed OvertimeRequest ${ot.id} (${ot.type}, ${ot.requestedMinutes} min)`);
      }

      console.log(`  ✓ Fixed TimeRecord date: ${storedStr} → ${correctStr}`);
    } else {
      console.log(`  [DRY RUN] Would fix TimeRecord date: ${storedStr} → ${correctStr}`);
      for (const ot of wrongDateOTs) {
        console.log(`  [DRY RUN] Would fix OvertimeRequest ${ot.id} (${ot.type}, ${ot.requestedMinutes} min)`);
      }
    }

    fixed++;
  }

  console.log('\n--- Summary ---');
  console.log(`Records checked: ${records.length}`);
  console.log(`Fixed: ${fixed}`);
  console.log(`Skipped (conflicts): ${conflicts}`);
  console.log(`Already correct: ${records.length - fixed - conflicts - skipped}`);
  if (conflicts > 0) {
    console.log('\n⚠ Some records had conflicts and were NOT fixed. Review them manually.');
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
