import prisma from '../config/database';
import { createNotification } from '../controllers/notification.controller';
import type { Server } from 'socket.io';

/**
 * Auto-reject expired overtime requests.
 *
 * Targets pre-requested OT (isAutoGenerated = false) that:
 * - Status is PENDING
 * - The OT date has already passed (date < today)
 * - Client never approved
 *
 * Runs daily. Rejects expired requests and notifies the employee.
 */
export const runExpiredOTRequestJob = async (io?: Server): Promise<void> => {
  try {
    const now = new Date();
    // Today at midnight UTC
    const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    // Find all PENDING pre-requested OT where the date has passed
    const expiredRequests = await prisma.overtimeRequest.findMany({
      where: {
        status: 'PENDING',
        isAutoGenerated: false,
        date: { lt: todayStart },
      },
    });

    if (expiredRequests.length === 0) return;

    console.log(`[ExpiredOT] Found ${expiredRequests.length} expired pending OT requests to auto-reject`);

    for (const request of expiredRequests) {
      try {
        // Reject the overtime request
        await prisma.overtimeRequest.update({
          where: { id: request.id },
          data: {
            status: 'REJECTED',
            rejectedAt: now,
            rejectionReason: 'Auto-rejected: overtime date has passed without client approval',
          },
        });

        // Cascade rejection to TimeRecord if exists
        const statusField = request.type === 'SHIFT_EXTENSION' ? 'shiftExtensionStatus' : 'extraTimeStatus';
        const existingTimeRecord = await prisma.timeRecord.findFirst({
          where: {
            employeeId: request.employeeId,
            clientId: request.clientId,
            date: request.date,
          },
        });

        if (existingTimeRecord) {
          const updateData: any = { [statusField]: 'DENIED' };
          // If the TimeRecord is still PENDING, approve the regular hours (only OT is denied)
          if (existingTimeRecord.status === 'PENDING') {
            updateData.status = 'APPROVED';
            updateData.approvedAt = now;
          }
          await prisma.timeRecord.update({
            where: { id: existingTimeRecord.id },
            data: updateData,
          });
        }

        // Notify the employee
        const employee = await prisma.employee.findUnique({
          where: { id: request.employeeId },
          select: { id: true, firstName: true, lastName: true, user: { select: { id: true } } },
        });

        if (employee?.user?.id) {
          const dateStr = request.date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
          await createNotification(
            employee.user.id,
            'OVERTIME_REJECTED',
            'Overtime Request Expired',
            `Your overtime request for ${dateStr} was auto-rejected because the date passed without client approval.`,
            { requestId: request.id },
            '/employee/time-records'
          );
        }

        console.log(`[ExpiredOT] Auto-rejected OT request ${request.id} for ${employee?.firstName} ${employee?.lastName} (${request.date.toISOString().split('T')[0]})`);
      } catch (err) {
        console.error(`[ExpiredOT] Failed to reject request ${request.id}:`, err);
      }
    }

    console.log(`[ExpiredOT] Completed: ${expiredRequests.length} requests auto-rejected`);
  } catch (error) {
    console.error('[ExpiredOT] Job failed:', error);
  }
};
