-- AlterTable
ALTER TABLE "client_holidays" ADD COLUMN     "holidayKey" TEXT,
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "client_policies" ADD COLUMN     "selectedFederalHolidays" TEXT;
