import api from './api';

const overtimeService = {
  // Get overtime requests
  async getOvertimeRequests(params = {}) {
    const queryParams = new URLSearchParams();
    if (params.status) queryParams.append('status', params.status);
    if (params.startDate) queryParams.append('startDate', params.startDate);
    if (params.endDate) queryParams.append('endDate', params.endDate);
    if (params.employeeId) queryParams.append('employeeId', params.employeeId);
    if (params.isAutoGenerated !== undefined) queryParams.append('isAutoGenerated', params.isAutoGenerated);
    if (params.limit) queryParams.append('limit', params.limit);
    if (params.offset) queryParams.append('offset', params.offset);

    const queryString = queryParams.toString();
    const url = queryString ? `/overtime-requests?${queryString}` : '/overtime-requests';
    return await api.get(url);
  },

  // Get overtime summary (for clients)
  async getOvertimeSummary(params = {}) {
    const queryParams = new URLSearchParams();
    if (params.startDate) queryParams.append('startDate', params.startDate);
    if (params.endDate) queryParams.append('endDate', params.endDate);

    const queryString = queryParams.toString();
    const url = queryString ? `/overtime-requests/summary?${queryString}` : '/overtime-requests/summary';
    return await api.get(url);
  },

  // Create overtime request
  async createOvertimeRequest(data) {
    const payload = {
      date: data.date,
      reason: data.reason,
      type: data.type || 'SHIFT_EXTENSION',
    };

    if (data.type === 'OFF_SHIFT') {
      // Off-shift: send start/end times, backend calculates minutes
      payload.requestedStartTime = data.requestedStartTime;
      payload.requestedEndTime = data.requestedEndTime;
    } else {
      // Shift extension: prefer start/end times if provided (calculate minutes), otherwise use requestedHours
      if (data.requestedStartTime && data.requestedEndTime) {
        const [startH, startM] = (data.requestedStartTime || '').split(':').map(Number);
        const [endH, endM] = (data.requestedEndTime || '').split(':').map(Number);
        let diff = (endH * 60 + endM) - (startH * 60 + startM);
        if (diff <= 0) diff += 24 * 60; // handle overnight
        payload.requestedMinutes = Math.round(diff);
        // set estimatedEndTime to help backend notifications
        payload.estimatedEndTime = data.requestedEndTime;
      } else {
        payload.requestedMinutes = Math.round((data.requestedHours || 0) * 60);
      }
    }

    if (data.employeeId) payload.employeeId = data.employeeId;
    if (data.clientId) payload.clientId = data.clientId;
    if (data.estimatedEndTime) payload.estimatedEndTime = data.estimatedEndTime;
    if (data.isAutoGenerated !== undefined) payload.isAutoGenerated = data.isAutoGenerated;

    return await api.post('/overtime-requests', payload);
  },

  // Approve overtime request
  async approveOvertimeRequest(id, notes) {
    return await api.put(`/overtime-requests/${id}/approve`, notes ? { notes } : {});
  },

  // Reject overtime request
  async rejectOvertimeRequest(id, reason, notes) {
    return await api.put(`/overtime-requests/${id}/reject`, { reason, ...(notes ? { notes } : {}) });
  },
};

export default overtimeService;
