import { useState, useEffect, useCallback, useRef } from "react";
import { useNavigate } from "react-router-dom";
import {
  Users,
  Clock,
  AlertCircle,
  CheckCircle,
  DollarSign,
  Activity,
  RefreshCw,
  Calendar,
  Timer,
  ChevronRight,
} from "lucide-react";
import { useAuth } from "../../../context/AuthContext";
import { Card, Badge, Button, Avatar } from "../../../components/common";
import { formatTimeInTimeZone } from "../../../utils/formatDateTime";
import clientPortalService from "../../../services/clientPortal.service";
import overtimeService from "../../../services/overtime.service";
import payrollService from "../../../services/payroll.service";

const ClientDashboard = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [stats, setStats] = useState({
    totalEmployees: 0,
    activeNow: 0,
    workingNow: 0,
    onBreakNow: 0,
    pendingApprovals: 0,
    weeklyHours: 0,
    monthlyBilling: 0,
  });
  const [activeEmployees, setActiveEmployees] = useState([]);
  const [upcomingOT, setUpcomingOT] = useState([]);
  const [pendingOT, setPendingOT] = useState(null);
  const [pendingLeaveCount, setPendingLeaveCount] = useState(0);
  const [nextPayrollDate, setNextPayrollDate] = useState(null);
  const [error, setError] = useState(null);

  const [currentTime, setCurrentTime] = useState(new Date());
  const fetchingRef = useRef(false);

  // Live EST clock
  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const fetchDashboardData = useCallback(async (showRefresh = false) => {
    if (fetchingRef.current) return;
    fetchingRef.current = true;
    try {
      if (showRefresh) setRefreshing(true);
      else setLoading(true);
      setError(null);

      const [
        statsRes,
        activeRes,
        upcomingOTRes,
        pendingOTRes,
        leaveRes,
        payrollRes,
      ] = await Promise.allSettled([
        clientPortalService.getDashboardStats(),
        clientPortalService.getActiveEmployees(),
        overtimeService.getOvertimeRequests({
          status: "PENDING",
          isAutoGenerated: "false",
        }),
        clientPortalService.getPendingOvertimeSummary(),
        clientPortalService.getApprovals({ status: "pending", type: "leave" }),
        payrollService.getCurrentPeriod(),
      ]);

      if (statsRes.status === "fulfilled" && statsRes.value.success) {
        setStats(statsRes.value.data);
      }

      if (activeRes.status === "fulfilled" && activeRes.value.success) {
        setActiveEmployees(activeRes.value.data || []);
      }

      if (upcomingOTRes.status === "fulfilled" && upcomingOTRes.value.success) {
        setUpcomingOT(upcomingOTRes.value.data.requests || []);
      }

      if (pendingOTRes.status === "fulfilled" && pendingOTRes.value.success) {
        setPendingOT(
          pendingOTRes.value.data.count > 0 ? pendingOTRes.value.data : null,
        );
      }

      if (leaveRes.status === "fulfilled" && leaveRes.value.success) {
        setPendingLeaveCount(leaveRes.value.data?.summary?.pending || 0);
      }

      if (
        payrollRes.status === "fulfilled" &&
        payrollRes.value.success &&
        payrollRes.value.data
      ) {
        setNextPayrollDate(payrollRes.value.data);
      }
    } catch (err) {
      console.error("Error fetching dashboard data:", err);
      setError("Failed to load dashboard data");
    } finally {
      setLoading(false);
      setRefreshing(false);
      fetchingRef.current = false;
    }
  }, []);

  useEffect(() => {
    fetchDashboardData();

    // Auto-refresh every 30 seconds for live data
    const interval = setInterval(() => {
      fetchDashboardData(true);
    }, 30000);

    return () => clearInterval(interval);
  }, [fetchDashboardData]);

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Welcome Section */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">
            Welcome back,{" "}
            {user?.client?.contactPerson?.split(" ")[0] || "there"}!
          </h2>
          <p className="text-gray-500">
            Here's what's happening with your team today.
          </p>
          <div className="flex items-center gap-2 mt-1">
            <Clock size={14} className="text-gray-400" />
            <span className="text-sm font-bold text-gray-500">
              {currentTime.toLocaleString("en-US", {
                timeZone: "America/New_York",
                weekday: "short",
                month: "short",
                day: "numeric",
                hour: "2-digit",
                minute: "2-digit",
                second: "2-digit",
                hour12: true,
              })}{" "}
              EST
            </span>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            icon={RefreshCw}
            onClick={() => fetchDashboardData(true)}
            disabled={refreshing}
            className={refreshing ? "animate-spin" : ""}
          >
            {refreshing ? "Refreshing..." : "Refresh"}
          </Button>
          <Button
            variant="outline"
            onClick={() => navigate("/client/analytics")}
          >
            View Reports
          </Button>
          <Button
            variant="primary"
            icon={CheckCircle}
            onClick={() => navigate("/client/approvals")}
          >
            View Approvals
          </Button>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">
          {error}
        </div>
      )}

      {/* Pending Actions — Unapproved Overtime Alert */}
      {pendingOT && pendingOT.count > 0 && (
        <div className="bg-amber-50 border-2 border-amber-300 rounded-xl p-5 shadow-sm">
          <div className="flex items-start gap-4">
            <div className="p-3 bg-amber-100 rounded-full flex-shrink-0 mt-0.5">
              <AlertCircle className="w-6 h-6 text-amber-600" />
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="text-lg font-bold text-amber-900">
                WORKED OVERTIME WITHOUT PRIOR APPROVAL — Action Required
              </h3>
              <p className="text-amber-800 mt-1">
                Please approve or deny before your billing cycle closes.
                Unapproved hours cannot be processed for payment.
              </p>
              <p>
                One or more employees worked overtime without prior approval.
                These hours have already been worked and will not be paid or
                billed unless you approve them. Please review and approve or
                deny the hours below.
              </p>
              {pendingOT.employees && pendingOT.employees.length > 0 && (
                <div className="mt-3 space-y-2">
                  {pendingOT.employees.map((emp, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-3 px-3 py-2 bg-white/70 border border-amber-200 rounded-lg"
                    >
                      <AlertCircle className="w-4 h-4 text-amber-500 flex-shrink-0" />
                      <span className="text-sm text-amber-900">
                        <strong>{emp.name}</strong> worked{" "}
                        <strong>{emp.hours}</strong> of unapproved overtime on
                        [date]. Approve or deny to process payment
                      </span>
                    </div>
                  ))}
                </div>
              )}
              <div className="mt-4 flex items-center gap-3">
                <Button
                  variant="primary"
                  icon={CheckCircle}
                  onClick={() =>
                    navigate("/client/approvals?type=auto-overtime")
                  }
                >
                  Review & Approve Now
                </Button>
                <span className="text-sm text-amber-700">
                  {pendingOT.count}{" "}
                  {pendingOT.count === 1 ? "entry" : "entries"} total{" "}
                  <strong>{pendingOT.totalHours}</strong>
                </span>
              </div>
              <p>
                This is not a future overtime request. These hours have already
                been worked.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Alerts */}
      {((pendingOT && pendingOT.count > 0) ||
        upcomingOT.length > 0 ||
        pendingLeaveCount > 0) && (
        <Card>
          <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wider mb-3">
            Alerts
          </h3>
          <div className="space-y-2">
            {pendingOT && pendingOT.count > 0 && (
              <button
                onClick={() => navigate("/client/approvals?type=auto-overtime")}
                className="flex items-center gap-3 w-full px-3 py-2.5 rounded-lg hover:bg-amber-50 transition-colors text-left group"
              >
                <AlertCircle className="w-5 h-5 text-amber-500 flex-shrink-0" />
                <span className="text-sm text-gray-800 flex-1">
                  <strong>{pendingOT.count}</strong> unapproved overtime{" "}
                  {pendingOT.count === 1 ? "needs" : "need"} review
                </span>
                <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-gray-600" />
              </button>
            )}
            {upcomingOT.length > 0 && (
              <button
                onClick={() => navigate("/client/approvals?type=overtime")}
                className="flex items-center gap-3 w-full px-3 py-2.5 rounded-lg hover:bg-orange-50 transition-colors text-left group"
              >
                <Timer className="w-5 h-5 text-orange-500 flex-shrink-0" />
                <span className="text-sm text-gray-800 flex-1">
                  <strong>{upcomingOT.length}</strong> overtime{" "}
                  {upcomingOT.length === 1 ? "request" : "requests"} pending
                  your approval
                </span>
                <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-gray-600" />
              </button>
            )}
            {pendingLeaveCount > 0 && (
              <button
                onClick={() => navigate("/client/approvals?type=leave")}
                className="flex items-center gap-3 w-full px-3 py-2.5 rounded-lg hover:bg-blue-50 transition-colors text-left group"
              >
                <Calendar className="w-5 h-5 text-blue-500 flex-shrink-0" />
                <span className="text-sm text-gray-800 flex-1">
                  <strong>{pendingLeaveCount}</strong> leave{" "}
                  {pendingLeaveCount === 1 ? "request" : "requests"} pending
                  your approval
                </span>
                <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-gray-600" />
              </button>
            )}
          </div>
        </Card>
      )}

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
        <div className="flex items-center gap-3 px-4 py-3 bg-gray-50 rounded-xl">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <Users className="w-5 h-5 text-gray-500" />
          </div>
          <div>
            <p className="text-xl font-bold text-gray-900">
              {stats.totalEmployees}
            </p>
            <p className="text-xs text-gray-500">Employees</p>
          </div>
        </div>
        <div className="flex items-center gap-3 px-4 py-3 bg-green-50 rounded-xl">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <Activity className="w-5 h-5 text-green-600" />
          </div>
          <div>
            <p className="text-xl font-bold text-green-700">
              {stats.activeNow}
            </p>
            <p className="text-xs text-green-600">
              {stats.workingNow} working
              {stats.onBreakNow > 0 ? `, ${stats.onBreakNow} break` : ""}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3 px-4 py-3 bg-amber-50 rounded-xl">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <AlertCircle className="w-5 h-5 text-amber-600" />
          </div>
          <div>
            <p className="text-xl font-bold text-amber-700">
              {stats.pendingApprovals}
            </p>
            <p className="text-xs text-amber-600">Pending Approvals</p>
          </div>
        </div>
        <div className="flex items-center gap-3 px-4 py-3 bg-blue-50 rounded-xl">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <Clock className="w-5 h-5 text-blue-600" />
          </div>
          <div>
            <p className="text-xl font-bold text-blue-700">
              {stats.weeklyHours}
            </p>
            <p className="text-xs text-blue-600">Weekly Hours</p>
          </div>
        </div>
        <div className="flex items-center gap-3 px-4 py-3 bg-purple-50 rounded-xl">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <DollarSign className="w-5 h-5 text-purple-600" />
          </div>
          <div>
            <p className="text-xl font-bold text-purple-700">
              {formatCurrency(stats.monthlyBilling)}
            </p>
            <p className="text-xs text-purple-600">Monthly Billing</p>
          </div>
        </div>
        <div className="flex items-center gap-3 px-4 py-3 bg-emerald-50 rounded-xl">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <Calendar className="w-5 h-5 text-emerald-600" />
          </div>
          <div>
            {nextPayrollDate ? (
              <>
                <p className="text-lg font-bold text-emerald-700">
                  {new Date(nextPayrollDate.cutoffDate).toLocaleDateString(
                    "en-US",
                    {
                      month: "short",
                      day: "numeric",
                      timeZone: "UTC",
                    },
                  )}
                </p>
                <p className="text-xs text-emerald-600">Next Payroll Date</p>
                <p className="text-[10px] text-gray-400">
                  {nextPayrollDate.daysUntilCutoff > 0
                    ? `${nextPayrollDate.daysUntilCutoff} days left`
                    : "Due today"}
                </p>
              </>
            ) : (
              <>
                <p className="text-lg font-bold text-gray-400">—</p>
                <p className="text-xs text-emerald-600">Next Payroll Date</p>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Active Workforce */}
        <div className="lg:col-span-2">
          <Card>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">
                Active Workforce
              </h3>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => navigate("/client/workforce")}
              >
                View All
              </Button>
            </div>
            {activeEmployees.length === 0 ? (
              <div className="text-center py-8 text-gray-500">
                <Activity className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                <p>No employees are currently working</p>
                <p className="text-sm mt-1">
                  Active employees will appear here
                </p>
              </div>
            ) : (
              <div className="space-y-3">
                {activeEmployees.slice(0, 5).map((employee) => (
                  <div
                    key={employee.id}
                    className="flex items-center justify-between p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                  >
                    <div className="flex items-center gap-4">
                      <Avatar
                        name={employee.name}
                        src={employee.profilePhoto}
                        status={
                          employee.status === "working" ? "online" : "away"
                        }
                      />
                      <div>
                        <p className="font-medium text-gray-900">
                          {employee.name}
                        </p>
                        <p className="text-sm text-gray-500">{employee.role}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-6">
                      <div className="text-right">
                        <p className="text-sm text-gray-500">Started</p>
                        <p className="font-semibold text-gray-900">
                          {employee.startTime
                            ? formatTimeInTimeZone(employee.startTime)
                            : "-"}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="text-sm text-gray-500">Duration</p>
                        <p className="font-semibold text-gray-900">
                          {employee.duration}
                        </p>
                      </div>
                      <Badge
                        variant={
                          employee.status === "working" ? "success" : "warning"
                        }
                        dot
                      >
                        {employee.status === "working" ? "Working" : "On Break"}
                      </Badge>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Card>
        </div>

        {/* Upcoming Pre-approved Overtime */}
        <Card>
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">
              Upcoming Pre-approved OT
            </h3>
            {upcomingOT.length > 0 && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => navigate("/client/approvals?type=overtime")}
              >
                View All
              </Button>
            )}
          </div>
          {upcomingOT.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              <Clock className="w-12 h-12 mx-auto mb-3 text-gray-300" />
              <p>No upcoming overtime</p>
              <p className="text-sm mt-1">
                Pre-approved OT requests will appear here
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {upcomingOT.slice(0, 5).map((ot) => {
                const empName = ot.employee
                  ? `${ot.employee.firstName} ${ot.employee.lastName}`
                  : "Unknown";
                const hrs = Math.floor(ot.requestedMinutes / 60);
                const mins = ot.requestedMinutes % 60;
                const duration = mins > 0 ? `${hrs}h ${mins}m` : `${hrs}h`;
                const dateLabel = new Date(ot.date).toLocaleDateString(
                  "en-US",
                  {
                    weekday: "short",
                    month: "short",
                    day: "numeric",
                    timeZone: "UTC",
                  },
                );
                return (
                  <div
                    key={ot.id}
                    className="p-3 border border-gray-100 rounded-lg hover:border-primary-200 transition-colors"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <Avatar
                          name={empName}
                          src={ot.employee?.profilePhoto}
                          size="sm"
                        />
                        <div>
                          <p className="font-medium text-gray-900 text-sm">
                            {empName}
                          </p>
                          <p className="text-xs text-gray-500">{dateLabel}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <Badge
                          variant={
                            ot.type === "OFF_SHIFT" ? "info" : "secondary"
                          }
                          size="sm"
                        >
                          {ot.type === "OFF_SHIFT" ? "Off-Shift" : "Extension"}
                        </Badge>
                        <p className="text-sm font-semibold text-gray-900 mt-1">
                          {duration}
                        </p>
                      </div>
                    </div>
                    {ot.reason && (
                      <p className="text-xs text-gray-500 mt-2 line-clamp-1">
                        {ot.reason}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </Card>
      </div>
    </div>
  );
};

export default ClientDashboard;
