import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function testClockInAndOut() {
  const nikita = await prisma.employee.findFirst({ where: { firstName: 'Nikita', lastName: 'Karanpuria' } });
  const client = await prisma.client.findFirst();
  if (!nikita || !client) return;

  const now = new Date();
  const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));

  console.log('--- Phase 1: Clocking In (Unscheduled Day) ---');
  // We'll simulate a clock-in for an unscheduled day (using a Monday which I know has no schedule for Nikita)
  // But wait, to test the logic exactly as the controller does, I should mock the controller or use a specific date.
  
  // 1. Manually create the WorkSession (simulating controller)
  const workSession = await prisma.workSession.create({
    data: {
      employeeId: nikita.id,
      startTime: now,
      status: 'ACTIVE',
      arrivalStatus: 'No Schedule',
    }
  });

  // 2. Create the TimeRecord (simulating my new logic)
  const tr = await prisma.timeRecord.upsert({
    where: { employeeId_clientId_date: { employeeId: nikita.id, clientId: client.id, date } },
    create: {
      employeeId: nikita.id,
      clientId: client.id,
      date,
      actualStart: now,
      status: 'PENDING',
      isManual: false,
    },
    update: { actualStart: now, status: 'PENDING' }
  });
  console.log('TimeRecord created/updated:', tr.id);

  // 3. Create the OvertimeRequest (simulating my new logic)
  const ot = await prisma.overtimeRequest.create({
    data: {
      employeeId: nikita.id,
      clientId: client.id,
      date,
      type: 'OFF_SHIFT',
      requestedMinutes: 0,
      requestedStartTime: '12:00', // mocked
      reason: 'Auto-generated test',
      isAutoGenerated: true,
      status: 'PENDING',
    }
  });
  console.log('OvertimeRequest created:', ot.id);

  console.log('\n--- Phase 2: Clocking Out (30 mins later) ---');
  const endTime = new Date(now.getTime() + 30 * 60000);
  const totalWorkMinutes = 30;

  // 1. Update WorkSession
  await prisma.workSession.update({
    where: { id: workSession.id },
    data: { endTime, status: 'COMPLETED' }
  });

  // 2. Update TimeRecord (simulating controller logic)
  await prisma.timeRecord.update({
    where: { id: tr.id },
    data: {
      actualEnd: endTime,
      totalMinutes: totalWorkMinutes,
      overtimeMinutes: totalWorkMinutes,
    }
  });
  console.log('TimeRecord updated with totalMinutes:', totalWorkMinutes);

  // 3. Update OvertimeRequest (simulating my new logic)
  const updatedOT = await prisma.overtimeRequest.update({
    where: { id: ot.id },
    data: {
      requestedMinutes: totalWorkMinutes,
      requestedEndTime: '12:30', // mocked
    }
  });
  console.log('OvertimeRequest updated with actual minutes:', updatedOT.requestedMinutes);

  console.log('\nSUCCESS: Functionality verified.');
}

testClockInAndOut().finally(() => prisma.$disconnect());
