import { useState, useEffect, useRef, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  CheckCircle,
  XCircle,
  Clock,
  AlertCircle,
  RefreshCw,
  RotateCcw,
  ChevronDown,
  Calendar,
  Timer,
  Loader2,
  Download,
  ChevronLeft,
  ChevronRight,
} from 'lucide-react';
import {
  Card,
  Button,
  Badge,
  Avatar,
  Modal,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableHeader,
  TableCell
} from '../../components/common';
import adminPortalService from '../../services/adminPortal.service';
import overtimeService from '../../services/overtime.service';
import clientService from '../../services/client.service';
import employeeService from '../../services/employee.service';

const Approvals = () => {
  const [searchParams] = useSearchParams();
  const [loading, setLoading] = useState(true);

  // Filters
  const [activeType, setActiveType] = useState(
    searchParams.get('type') || 'leave'
  );
  const [statusFilter, setStatusFilter] = useState('all');
  const [employeeFilter, setEmployeeFilter] = useState('all');
  const [clientFilterId, setClientFilterId] = useState('all');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [page, setPage] = useState(1);
  const [totalItems, setTotalItems] = useState(0);
  const pageSize = 20;
  const [employeesList, setEmployeesList] = useState([]);
  const [clientsList, setClientsList] = useState([]);

  // Data
  const [items, setItems] = useState([]);
  const [clients, setClients] = useState([]);

  // Modals
  const [selectedItem, setSelectedItem] = useState(null);
  const [showApprovalModal, setShowApprovalModal] = useState(false);
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [showRevisionModal, setShowRevisionModal] = useState(false);
  const [rejectionReason, setRejectionReason] = useState('');
  const [revisionReason, setRevisionReason] = useState('');
  const [actionNotes, setActionNotes] = useState('');
  const [processing, setProcessing] = useState(false);
  const [selectedItems, setSelectedItems] = useState([]);

  const fetchingRef = useRef(false);

  // Pending counts for tab badges
  const [pendingCounts, setPendingCounts] = useState({ leave: 0, overtime: 0, autoOvertime: 0 });

  const fetchPendingCounts = useCallback(async () => {
    try {
      const [otRes, autoOtRes, pendingActionsRes] = await Promise.all([
        overtimeService.getOvertimeRequests({ status: 'PENDING', isAutoGenerated: 'false', limit: 1 }),
        overtimeService.getOvertimeRequests({ status: 'PENDING', isAutoGenerated: 'true', limit: 1 }),
        adminPortalService.getPendingActions(),
      ]);
      setPendingCounts({
        leave: pendingActionsRes?.counts?.pendingLeave || 0,
        overtime: otRes?.data?.total || 0,
        autoOvertime: autoOtRes?.data?.total || 0,
      });
    } catch (e) { /* ignore */ }
  }, []);

  // Fetch employees, clients, and pending counts
  useEffect(() => {
    (async () => {
      try {
        const [empRes, clientRes] = await Promise.all([
          employeeService.getEmployees({ limit: 500 }),
          clientService.getClients({ limit: 100 }),
        ]);
        if (empRes?.success) setEmployeesList(empRes.data?.employees || []);
        if (clientRes?.success) setClientsList(clientRes.data?.clients || []);
      } catch (e) { /* ignore */ }
    })();
    fetchPendingCounts();
  }, [fetchPendingCounts]);

  const isOTType = activeType === 'overtime' || activeType === 'autoOvertime';

  const fetchData = useCallback(async () => {
    if (fetchingRef.current) return;
    fetchingRef.current = true;
    setLoading(true);
    try {
      if (activeType === 'overtime' || activeType === 'autoOvertime') {
        const statusMap = { pending: 'PENDING', approved: 'APPROVED', rejected: 'REJECTED' };
        const params = {
          isAutoGenerated: activeType === 'autoOvertime' ? 'true' : 'false',
          startDate: startDate || undefined,
          endDate: endDate || undefined,
          limit: pageSize,
          offset: (page - 1) * pageSize,
        };
        if (statusFilter !== 'all') params.status = statusMap[statusFilter] || 'PENDING';
        if (employeeFilter !== 'all') params.employeeId = employeeFilter;
        const res = await overtimeService.getOvertimeRequests(params);
        if (res.success) {
          let requests = res.data.requests || [];
          if (clientFilterId !== 'all') {
            requests = requests.filter(r => r.clientId === clientFilterId);
          }
          setItems(requests);
          setTotalItems(res.data.total || requests.length);
        }
      } else {
        // Leave or timesheet
        const params = {
          type: activeType === 'timesheet' ? 'timesheet' : 'leave',
          page,
          limit: pageSize,
        };
        if (statusFilter !== 'all') params.status = statusFilter;
        if (clientFilterId !== 'all') params.clientId = clientFilterId;
        const res = await adminPortalService.getApprovals(params);
        if (res?.success) {
          let approvals = res.data.approvals || [];
          if (employeeFilter !== 'all') {
            const emp = employeesList.find(e => (e.id || e.employeeId) === employeeFilter);
            if (emp) {
              const empName = `${emp.firstName} ${emp.lastName}`.toLowerCase();
              approvals = approvals.filter(a => a.employee?.toLowerCase() === empName);
            }
          }
          setItems(approvals);
          setTotalItems(res.data.total || approvals.length);
        }
      }
    } catch (error) {
      console.error('Failed to fetch:', error);
    } finally {
      setLoading(false);
      fetchingRef.current = false;
    }
  }, [activeType, statusFilter, startDate, endDate, employeeFilter, clientFilterId, page]);

  useEffect(() => {
    setSelectedItems([]);
    fetchData();
  }, [fetchData]);

  // Handlers
  const handleApprove = (item) => { setSelectedItem(item); setActionNotes(''); setShowApprovalModal(true); };
  const handleReject = (item) => { setSelectedItem(item); setRejectionReason(''); setActionNotes(''); setShowRejectModal(true); };
  const handleRequestRevision = (item) => { setSelectedItem(item); setRevisionReason(''); setShowRevisionModal(true); };

  const confirmApproval = async () => {
    if (!selectedItem) return;
    setProcessing(true);
    try {
      let response;
      if (isOTType) {
        response = await overtimeService.approveOvertimeRequest(selectedItem.id, actionNotes.trim() || undefined);
      } else if (selectedItem.type === 'leave') {
        response = await adminPortalService.approveLeaveRequest(selectedItem.id);
      } else {
        response = await adminPortalService.approveTimeRecord(selectedItem.id);
      }
      if (response?.success) {
        setShowApprovalModal(false);
        fetchData();
        fetchPendingCounts();
        window.dispatchEvent(new Event('approvals-updated'));
      }
    } catch (error) { console.error('Approve error:', error); }
    finally { setProcessing(false); }
  };

  const confirmRejection = async () => {
    if (!selectedItem || !rejectionReason.trim()) return;
    setProcessing(true);
    try {
      let response;
      if (isOTType) {
        response = await overtimeService.rejectOvertimeRequest(selectedItem.id, rejectionReason, actionNotes.trim() || undefined);
      } else if (selectedItem.type === 'leave') {
        response = await adminPortalService.rejectLeaveRequest(selectedItem.id, rejectionReason);
      } else {
        response = await adminPortalService.rejectTimeRecord(selectedItem.id, rejectionReason);
      }
      if (response?.success) {
        setShowRejectModal(false);
        setRejectionReason('');
        fetchData();
        fetchPendingCounts();
        window.dispatchEvent(new Event('approvals-updated'));
      }
    } catch (error) { console.error('Reject error:', error); }
    finally { setProcessing(false); }
  };

  const confirmRequestRevision = async () => {
    if (!selectedItem || !revisionReason.trim()) return;
    setProcessing(true);
    try {
      const response = await adminPortalService.requestRevisionTimeRecord(selectedItem.id, revisionReason);
      if (response?.success) { setShowRevisionModal(false); fetchData(); }
    } catch (error) { console.error('Revision error:', error); }
    finally { setProcessing(false); }
  };

  const handleBulkApprove = async () => {
    if (selectedItems.length === 0) return;
    setProcessing(true);
    try {
      if (isOTType) {
        for (const id of selectedItems) await overtimeService.approveOvertimeRequest(id);
      } else {
        await adminPortalService.bulkApproveTimeRecords(selectedItems);
      }
      setSelectedItems([]);
      fetchData();
      fetchPendingCounts();
      window.dispatchEvent(new Event('approvals-updated'));
    } catch (error) { console.error('Bulk approve error:', error); }
    finally { setProcessing(false); }
  };

  const toggleSelectItem = (id) => {
    setSelectedItems(prev => prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]);
  };
  const toggleSelectAll = () => {
    setSelectedItems(selectedItems.length === items.length ? [] : items.map(i => i.id));
  };

  const totalPages = Math.ceil(totalItems / pageSize);

  const handleExport = () => {
    const headers = isOTType
      ? ['Employee', 'Client', 'Type', 'Reason', 'Date', 'Hours', 'Status', 'Submitted']
      : ['Employee', 'Client', 'Description', 'Date', 'Status', 'Submitted'];
    const rows = items.map((item) => {
      const empName = isOTType ? (item.employee ? `${item.employee.firstName} ${item.employee.lastName}` : 'Unknown') : item.employee;
      const client = isOTType ? (item.clientName || 'Unknown') : item.client;
      if (isOTType) {
        return [empName, client, item.type === 'OFF_SHIFT' ? 'Off-Shift' : 'Extension', item.reason, formatDate(item.date), formatMinutesToHours(item.requestedMinutes), item.status, formatDateTime(item.createdAt)].map(v => `"${(v || '').toString().replace(/"/g, '""')}"`).join(',');
      }
      return [empName, client, item.description, formatDate(item.date), item.status || item.approvalStatus, formatDateTime(item.submittedAt)].map(v => `"${(v || '').toString().replace(/"/g, '""')}"`).join(',');
    });
    const csv = [headers.join(','), ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `approvals-${activeType}-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '-';
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
  };

  const formatDateTime = (dateStr) => {
    if (!dateStr) return '-';
    const d = new Date(dateStr);
    return d.toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true });
  };

  const formatMinutesToHours = (minutes) => {
    if (!minutes) return '0h';
    const hrs = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return mins > 0 ? `${hrs}h ${mins}m` : `${hrs}h`;
  };

  const getStatusBadge = (status) => {
    const s = (status || '').toUpperCase();
    if (s === 'APPROVED' || s === 'AUTO_APPROVED') return <Badge variant="success">Approved</Badge>;
    if (s === 'PENDING') return <Badge variant="warning">Pending</Badge>;
    if (s === 'REJECTED') return <Badge variant="danger">Rejected</Badge>;
    if (s === 'REVISION_REQUESTED') return <Badge variant="warning" className="bg-amber-100 text-amber-800">Revision</Badge>;
    return <Badge variant="default">{status}</Badge>;
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Approvals</h2>
          <p className="text-gray-500">Review and manage all approval requests</p>
        </div>
        <div className="flex items-center gap-3">
          {selectedItems.length > 0 && (statusFilter === 'pending' || statusFilter === 'all') && (
            <Button variant="success" icon={CheckCircle} onClick={handleBulkApprove} disabled={processing}>
              Approve Selected ({selectedItems.length})
            </Button>
          )}
          <Button variant="outline" size="sm" icon={Download} onClick={handleExport}>
            Export CSV
          </Button>
          <Button variant="outline" icon={RefreshCw} onClick={fetchData}>
            Refresh
          </Button>
        </div>
      </div>

      {/* Type Toggle */}
      <div className="flex gap-2 p-1 bg-gray-100 rounded-lg w-fit flex-wrap">
        {[
          { key: 'leave', label: 'Leave Requests', icon: Calendar },
          { key: 'overtime', label: 'Overtime Requests', icon: Timer },
          { key: 'autoOvertime', label: 'OT Without Prior Approval', icon: AlertCircle },
          // { key: 'timesheet', label: 'Timesheet Review', icon: Clock },
        ].map(({ key, label, icon: Icon }) => (
          <button
            key={key}
            onClick={() => { setActiveType(key); setStatusFilter('all'); setEmployeeFilter('all'); setClientFilterId('all'); setSelectedItems([]); setPage(1); }}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2 whitespace-nowrap ${activeType === key ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-600 hover:text-gray-900'}`}
          >
            <Icon className="w-4 h-4" />
            {label}
            {pendingCounts[key] > 0 && (
              <span className="ml-1 px-1.5 py-0.5 text-xs font-bold rounded-full bg-red-500 text-white min-w-[20px] text-center">
                {pendingCounts[key]}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* Filters */}
      <div className="flex items-center gap-2 flex-wrap">
        <div className="relative">
          <select
            className="appearance-none border border-gray-200 rounded-lg pl-3 pr-8 py-2 text-sm bg-white cursor-pointer focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
            value={employeeFilter}
            onChange={(e) => { setEmployeeFilter(e.target.value); setSelectedItems([]); setPage(1); }}
          >
            <option value="all">All Employees</option>
            {employeesList.map((emp) => (
              <option key={emp.id || emp.employeeId} value={emp.id || emp.employeeId}>
                {emp.firstName} {emp.lastName}
              </option>
            ))}
          </select>
          <ChevronDown className="w-4 h-4 text-gray-400 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" />
        </div>
        <div className="relative">
          <select
            className="appearance-none border border-gray-200 rounded-lg pl-3 pr-8 py-2 text-sm bg-white cursor-pointer focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
            value={clientFilterId}
            onChange={(e) => { setClientFilterId(e.target.value); setSelectedItems([]); setPage(1); }}
          >
            <option value="all">All Clients</option>
            {clientsList.map((c) => (
              <option key={c.id} value={c.id}>{c.companyName}</option>
            ))}
          </select>
          <ChevronDown className="w-4 h-4 text-gray-400 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" />
        </div>
        <div className="relative">
          <select
            className="appearance-none border border-gray-200 rounded-lg pl-3 pr-8 py-2 text-sm bg-white cursor-pointer focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary"
            value={statusFilter}
            onChange={(e) => { setStatusFilter(e.target.value); setSelectedItems([]); setPage(1); }}
          >
            <option value="all">All Status</option>
            <option value="pending">Pending</option>
            <option value="approved">Approved</option>
            <option value="rejected">Rejected</option>
            {activeType === 'timesheet' && <option value="revision_requested">Revision Requested</option>}
          </select>
          <ChevronDown className="w-4 h-4 text-gray-400 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" />
        </div>
        <input
          type="date"
          className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary w-[150px]"
          value={startDate}
          onChange={(e) => setStartDate(e.target.value)}
        />
        <input
          type="date"
          className="border border-gray-200 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary w-[150px]"
          value={endDate}
          onChange={(e) => setEndDate(e.target.value)}
        />
        {(employeeFilter !== 'all' || clientFilterId !== 'all' || startDate || endDate || statusFilter !== 'all') && (
          <button
            className="text-sm text-primary hover:text-primary-dark font-medium"
            onClick={() => { setEmployeeFilter('all'); setClientFilterId('all'); setStartDate(''); setEndDate(''); setStatusFilter('all'); setPage(1); }}
          >
            Clear ×
          </button>
        )}
      </div>

      {/* Table */}
      <Card padding="none">
        {loading ? (
          <div className="p-12 text-center">
            <Loader2 className="w-8 h-8 text-primary animate-spin mx-auto" />
          </div>
        ) : items.length > 0 ? (
          <div className="overflow-x-auto">
            <Table>
              <TableHead>
                <TableRow>
                  {(statusFilter === 'pending' || statusFilter === 'all') && (
                    <TableHeader className="!w-10 !px-3">
                      <input type="checkbox" className="rounded border-gray-300" checked={selectedItems.length === items.length && items.length > 0} onChange={toggleSelectAll} />
                    </TableHeader>
                  )}
                  <TableHeader className="!px-3">Employee</TableHeader>
                  <TableHeader className="!px-3">Client</TableHeader>
                  {isOTType && <TableHeader className="!px-3">Type</TableHeader>}
                  <TableHeader className="!px-3">{isOTType ? 'Reason' : 'Description'}</TableHeader>
                  <TableHeader className="!px-3">Date</TableHeader>
                  {isOTType && <TableHeader className="!px-3">Hours</TableHeader>}
                  <TableHeader className="!px-3">Status</TableHeader>
                  <TableHeader className="!px-3">Submitted</TableHeader>
                  {(statusFilter === 'pending' || statusFilter === 'all') && <TableHeader className="!px-3">Actions</TableHeader>}
                </TableRow>
              </TableHead>
              <TableBody>
                {items.map((item) => {
                  const empName = isOTType
                    ? (item.employee ? `${item.employee.firstName} ${item.employee.lastName}` : 'Unknown')
                    : (typeof item.employee === 'string' ? item.employee : item.employee?.firstName ? `${item.employee.firstName} ${item.employee.lastName}` : 'Unknown');
                  const empPhoto = isOTType ? item.employee?.profilePhoto : (item.profilePhoto || item.employee?.profilePhoto);
                  const itemStatus = isOTType ? item.status : (item.status || item.approvalStatus || 'PENDING');

                  return (
                    <TableRow key={item.id}>
                      {(statusFilter === 'pending' || statusFilter === 'all') && (
                        <TableCell className="!px-3">
                          <input type="checkbox" className="rounded border-gray-300" checked={selectedItems.includes(item.id)} onChange={() => toggleSelectItem(item.id)} />
                        </TableCell>
                      )}
                      <TableCell className="!px-3">
                        <div className="flex items-center gap-2">
                          <Avatar name={empName} size="sm" src={empPhoto} />
                          <span className="font-medium text-sm">{empName}</span>
                        </div>
                      </TableCell>
                      <TableCell className="!px-3"><span className="text-gray-600 text-sm">{isOTType ? (item.clientName || 'Unknown') : item.client}</span></TableCell>
                      {isOTType && (
                        <TableCell className="!px-3">
                          <Badge variant={item.type === 'OFF_SHIFT' ? 'info' : 'secondary'} size="xs">
                            {item.type === 'OFF_SHIFT' ? 'Off-Shift' : 'Extension'}
                          </Badge>
                        </TableCell>
                      )}
                      <TableCell className="!px-3 !whitespace-normal">
                        <p className="text-gray-900 text-sm line-clamp-2 whitespace-nowrap">{isOTType ? item.reason : item.description}</p>
                        {!isOTType && item.details && <p className="text-xs text-gray-500 mt-0.5">{item.details}</p>}
                      </TableCell>
                      <TableCell className="!px-3">
                        <span className="text-sm">{formatDate(item.date)}</span>
                        {isOTType && (item.requestedStartTime || item.estimatedEndTime) && (
                          <p className="text-xs text-gray-400">
                            {item.requestedStartTime && item.requestedEndTime
                              ? `${item.requestedStartTime} - ${item.requestedEndTime}`
                              : item.estimatedEndTime
                                ? `until ${item.estimatedEndTime}`
                                : ''}
                          </p>
                        )}
                      </TableCell>
                      {isOTType && (
                        <TableCell className="!px-3">
                          <span className="font-semibold text-sm">{formatMinutesToHours(item.requestedMinutes)}</span>
                        </TableCell>
                      )}
                      <TableCell className="!px-3">{getStatusBadge(itemStatus)}</TableCell>
                      <TableCell className="!px-3">
                        <span className="text-xs text-gray-500">{formatDateTime(isOTType ? item.createdAt : item.submittedAt)}</span>
                      </TableCell>
                      {(statusFilter === 'pending' || statusFilter === 'all') && (
                        <TableCell className="!px-3">
                          {(isOTType ? item.status === 'PENDING' : (itemStatus || '').toUpperCase() === 'PENDING') ? (
                            <div className="flex gap-1.5">
                              <Button variant="success" size="xs" icon={CheckCircle} onClick={() => handleApprove(item)} disabled={processing}>
                                Approve
                              </Button>
                              {activeType === 'timesheet' ? (
                                <Button variant="ghost" size="xs" icon={RotateCcw} onClick={() => handleRequestRevision(item)} className="text-amber-600 hover:text-amber-700" disabled={processing}>
                                  Revise
                                </Button>
                              ) : (
                                <Button variant="ghost" size="xs" icon={XCircle} onClick={() => handleReject(item)} disabled={processing}>
                                  Reject
                                </Button>
                              )}
                            </div>
                          ) : (
                            <span className="text-gray-300">—</span>
                          )}
                        </TableCell>
                      )}
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        ) : (
          <div className="p-12 text-center">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-8 h-8 text-gray-400" />
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-1">No items found</h3>
            <p className="text-gray-500">
              {statusFilter === 'pending' ? 'All caught up! No pending items.' : `No ${statusFilter} items to show.`}
            </p>
          </div>
        )}
      </Card>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between">
          <p className="text-sm text-gray-500">
            Showing {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, totalItems)} of {totalItems} items
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setPage(p => Math.max(1, p - 1))}
              disabled={page === 1}
              className="p-2 rounded-lg border border-gray-200 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            {Array.from({ length: Math.min(totalPages, 5) }, (_, i) => {
              let pageNum;
              if (totalPages <= 5) {
                pageNum = i + 1;
              } else if (page <= 3) {
                pageNum = i + 1;
              } else if (page >= totalPages - 2) {
                pageNum = totalPages - 4 + i;
              } else {
                pageNum = page - 2 + i;
              }
              return (
                <button
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  className={`w-9 h-9 rounded-lg text-sm font-medium transition-colors ${page === pageNum ? 'bg-primary text-white' : 'border border-gray-200 hover:bg-gray-50 text-gray-700'}`}
                >
                  {pageNum}
                </button>
              );
            })}
            <button
              onClick={() => setPage(p => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              className="p-2 rounded-lg border border-gray-200 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* Approval Modal */}
      <Modal
        isOpen={showApprovalModal}
        onClose={() => setShowApprovalModal(false)}
        title="Confirm Approval"
        size="sm"
        footer={
          <>
            <Button variant="ghost" onClick={() => setShowApprovalModal(false)}>Cancel</Button>
            <Button variant="success" icon={CheckCircle} onClick={confirmApproval} disabled={processing}>
              {processing ? 'Approving...' : 'Approve'}
            </Button>
          </>
        }
      >
        {selectedItem && (
          <div className="space-y-4">
            <div className="p-4 bg-gray-50 rounded-lg space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Employee</span>
                <span className="font-medium">{isOTType ? `${selectedItem.employee?.firstName} ${selectedItem.employee?.lastName}` : selectedItem.employee}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Date</span>
                <span className="font-medium">{formatDate(selectedItem.date)}</span>
              </div>
              {isOTType && (
                <>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-500">Type</span>
                    <span className="font-medium">{selectedItem.type === 'OFF_SHIFT' ? 'Off-Shift' : 'Shift Extension'}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-500">Duration</span>
                    <span className="font-medium">{formatMinutesToHours(selectedItem.requestedMinutes)}</span>
                  </div>
                </>
              )}
            </div>
            {isOTType && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes <span className="text-gray-400 font-normal">(optional)</span></label>
                <textarea className="input w-full resize-none" rows={2} value={actionNotes} onChange={(e) => setActionNotes(e.target.value)} placeholder="Additional notes..." />
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* Reject Modal */}
      <Modal
        isOpen={showRejectModal}
        onClose={() => setShowRejectModal(false)}
        title="Reject Request"
        size="sm"
        footer={
          <>
            <Button variant="ghost" onClick={() => setShowRejectModal(false)}>Cancel</Button>
            <Button variant="danger" icon={XCircle} onClick={confirmRejection} disabled={processing || !rejectionReason.trim()}>
              {processing ? 'Rejecting...' : 'Reject'}
            </Button>
          </>
        }
      >
        {selectedItem && (
          <div className="space-y-4">
            <div className="p-4 bg-gray-50 rounded-lg">
              <p className="text-sm text-gray-500">Employee</p>
              <p className="font-medium">{isOTType ? `${selectedItem.employee?.firstName} ${selectedItem.employee?.lastName}` : selectedItem.employee}</p>
            </div>
            <div>
              <label className="label">Rejection Reason *</label>
              <textarea className="input min-h-[80px] resize-none w-full" placeholder="Reason for rejection..." value={rejectionReason} onChange={(e) => setRejectionReason(e.target.value)} />
            </div>
            {isOTType && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes <span className="text-gray-400 font-normal">(optional)</span></label>
                <textarea className="input w-full resize-none" rows={2} value={actionNotes} onChange={(e) => setActionNotes(e.target.value)} placeholder="Additional notes..." />
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* Revision Modal */}
      <Modal
        isOpen={showRevisionModal}
        onClose={() => setShowRevisionModal(false)}
        title="Request Revisions"
        size="sm"
        footer={
          <>
            <Button variant="ghost" onClick={() => setShowRevisionModal(false)}>Cancel</Button>
            <Button variant="primary" icon={RotateCcw} onClick={confirmRequestRevision} disabled={processing || !revisionReason.trim()} className="bg-amber-500 hover:bg-amber-600 border-amber-500">
              {processing ? 'Requesting...' : 'Request Revisions'}
            </Button>
          </>
        }
      >
        {selectedItem && (
          <div className="space-y-4">
            <div className="p-4 bg-gray-50 rounded-lg">
              <p className="text-sm text-gray-500">Employee</p>
              <p className="font-medium">{selectedItem.employee}</p>
              {selectedItem.description && (
                <>
                  <p className="text-sm text-gray-500 mt-2">Description</p>
                  <p className="font-medium">{selectedItem.description}</p>
                </>
              )}
            </div>
            <div>
              <label className="label">Revision Notes *</label>
              <textarea className="input min-h-[80px] resize-none w-full" placeholder="Describe what needs to be revised..." value={revisionReason} onChange={(e) => setRevisionReason(e.target.value)} />
            </div>
            <div className="p-3 bg-amber-50 rounded-lg flex items-start gap-2">
              <AlertCircle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-amber-700">The employee will be notified and can resubmit their timesheet.</p>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default Approvals;
