name: reactcicddddd
 
on:
    push:
        branches: [main]
 
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy NodeJS app
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: '13.232.55.215'
                  username: 'ubuntu'
                  key: ${{ secrets.SSHKEY }}
                  script: | 
                   bash /home/ubuntu/hello-team.sh
